### ISSUE TITLE
Error when calling getData() function

### ISSUE THREAD

**Issue by juanm4** [mikehaertl/php-pdftk#132]
Hi, I detect a bug (not sure) whe I call to this function: 

`getData($utf8 = true)`

When I call that function I get the next error:

`Unhandled Java Exception in create_output():
java.lang.ClassCastException: pdftk.com.lowagie.text.pdf.PdfNumber cannot be cast to pdftk.com.lowagie.text.pdf.PdfDictionary
	at com.gitlab.pdftk_java.bookmarks.ReadOutlines(bookmarks.java:237)
	at com.gitlab.pdftk_java.report.ReportOutlines(report.java:776)
	at com.gitlab.pdftk_java.report.ReportOnPdf(report.java:1049)
	at com.gitlab.pdftk_java.TK_Session.create_output(TK_Session.java:3365)
	at com.gitlab.pdftk_java.pdftk.main(pdftk.java:177)`

What is the problem? Am I do something wrong?

Thanks!

**Comment by marcvinyals** [comment]
@juanm4 it seems that you are using an experimental rewrite of pdftk in java, so as a short term fix you could try replacing it with the original pdftk-2.02. For a longer term solution, would you mind reporting this issue at https://gitlab.com/pdftk-java/pdftk, including the PDF that triggers the error and whether using the original version solves it?

**Comment by mikehaertl** [comment]
@marcvinyals Thanks for having an eye on our little project here :). I wasn't aware that there was some work being done on pdftk. If I understand correctly your port requires a JRE, right?

**Comment by marcvinyals** [comment]
@mikehaertl Your tests were helpful in writing the port, so thanks to you as well :) I do not plan to extend pdftk, just to keep it working after gcj goes away and to fix the occasional bug. You are right in that the port requires a JRE.

**Comment by juanm4** [comment]
> @juanm4 it seems that you are using an experimental rewrite of pdftk in java, so as a short term fix you could try replacing it with the original pdftk-2.02. For a longer term solution, would you mind reporting this issue at https://gitlab.com/pdftk-java/pdftk, including the PDF that triggers the error and whether using the original version solves it?

You are totally right!! I have been check versions and it wasn't the original. I have replaced my version to the original and it works perfectly. Thank so much!!!!!
